- hosts: local
  tasks:
    - name: Pull Docker image
      docker_image:
        name: demo-app
        tag: latest
        source: local

    - name: Run Docker container
      docker_container:
        name: demo-app
        image: demo-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
