name: Java Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Java app
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t demo-app:latest .

      - name: Save Docker image as artifact
        run: docker save demo-app:latest -o demo-app.tar

      - uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: demo-app.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: .

      - name: Load Docker image
        run: docker load -i demo-app.tar

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Deploy with Ansible
        run: ansible-playbook -i inventory.ini deploy.yml
